announcement:
  enabled: true
  description: >-
    Welcoming the 2023/2024 Overflow EXCO!
  url: https://np-overflow.club

navbar:
  title: Overflow
  menu_items:
    - name: Events
      to: /events
      icon: tabler:calendar-event
    - name: Team
      to: /team
      icon: tabler:users
    - name: Handbook
      to: https://handbook.np-overflow.club
      icon: tabler:book-2

  join_us:
    enabled: true
    text: Join Us!
    url: https://np-overflow.club
    icon: tabler:click

socials:
  discord_url: https://discord.gg/gUzY5FrvbM
  instagram_url: https://www.instagram.com/npoverflow/
