navbar:
  title: Overflow
  menu_items:
    - name: Workshops
      to: "#workshops"
      icon: tabler:books
    - name: Bootcamps
      to: /
      icon: tabler:tent
    - name: Team
      to: /team
      icon: tabler:users

  join_us:
    enabled: true
    text: Join Us!
    url: https://np-overflow.club
    icon: tabler:click

socials:
  discord_url: https://discord.gg/gUzY5FrvbM
  instagram_url: https://www.instagram.com/npoverflow/
