title: Overflow
logos:
  light: /logos/light.webp
  dark: /logos/dark.webp
  system: /logos/light.webp

menu_items:
  - name: Workshops
    to: "#workshops"
    icon: tabler:books
  - name: Bootcamps
    to: /
    icon: tabler:tent
  - name: Team
    to: /team
    icon: tabler:users

join_url: https://np-overflow.club
discord_url: https://discord.gg/gUzY5FrvbM
instagram_url: https://www.instagram.com/npoverflow/
